import ply.lex as lex

tokens={
    
    "DEFVAR","NAME","MOVE","SKIP","TURND","FACE0","PUT","PICK","MOVEDIR","RUNDIR","MOVEFACE",
    "NULL","MOVEFACE","DIM","MYXPOS","MYYPOS","MYCHIPS","MYBALLOONS","BALOONSHERE","CHIPSHERE",
    "SPACES",""
}


